
enyo.depends(
  'source/utils/AppSettings.js',
  'source/database/persistence/persistence.js',
  'source/database/persistence/persistence.store.sql.js',
  'source/database/persistence/persistence.store.websql.js',
  'source/database/persistence/persistence.search.js',
  'stylesheets/neolog.css',
  'source/utils/funcs.js',
  'source/screens/Neolog.js',
  'source/screens/Loading.js',
  'source/screens/LettersAndNests.js',
  'source/screens/Words.js',
  'source/screens/WordDetails.js',
  'source/screens/SendComment.js',
  'source/screens/ViewComments.js',
  'source/screens/SendWord.js',
  'source/screens/Search.js',
  'source/screens/SearchResults.js',
  'source/screens/Preferences.js',
  'source/screens/About.js'
);